version: '3.3'

services:
  plantuml-server:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    image: heinrichad/plantuml-server:tomcat-local
    container_name: plantuml-server
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml
