FROM maven:3-jdk-8 AS builder

COPY pom.xml /app/
COPY src /app/src/

WORKDIR /app
RUN mvn --batch-mode --define java.net.useSystemProxies=true package

########################################################################################

FROM jetty
MAINTAINER D.Ducatel

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends graphviz fonts-wqy-zenhei && \
    apt-get clean

USER jetty

COPY --from=builder /app/target/plantuml.war /var/lib/jetty/webapps/ROOT.war
