version: "3"

services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    environment:
      - TZ=Europe/Berlin

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
